name: Keep Server Warm

on:
  schedule:
    - cron: '*/3 * * * *'  # Run every 3 minutes to ensure we don't miss the 15-minute window
  workflow_dispatch:  # Allows manual triggering

jobs:
  warmup:
    runs-on: ubuntu-latest
    timeout-minutes: 1  # Limit execution time to 1 minute
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true  # Cancel running job if new one starts
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.7'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --only=production --no-audit  # Faster than npm install
          npm install https

      - name: Run warmup script
        run: node scripts/keep-warm.js
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          NODE_ENV: production 