name: Keep Server Warm

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  warmup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.7'
          cache: 'npm'

      - name: Install dependencies
        run: npm install https

      - name: Run warmup script
        run: node scripts/keep-warm.js
        env:
          BASE_URL: ${{ secrets.BASE_URL }} 