name: Keep Server Warm

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes (minimum interval supported by GitHub Actions)
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main, master ]  # Also run on pushes to main/master to verify it works

jobs:
  warmup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true  # Cancel running job if new one starts

    steps:
      - name: Debug Trigger
        run: |
          echo "Event that triggered the workflow: ${{ github.event_name }}"
          echo "Workflow triggered at: $(date -u)"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub branch: ${GITHUB_REF#refs/heads/}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.7'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --only=production --no-audit  # Faster than npm install
          npm install https

      - name: Run warmup script
        run: node scripts/keep-warm.js
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          NODE_ENV: production 